# Generated by Django 4.1.4 on 2024-02-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0003_rename_sample_imageconfigs_sampler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageconfigs',
            name='seed',
        ),
    ]
