# Generated by Django 4.1.4 on 2024-02-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0004_remove_imageconfigs_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('negative_prompt', models.CharField(max_length=500)),
                ('seed', models.CharField(max_length=500)),
                ('unix_id', models.CharField(max_length=500)),
                ('config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_api.imageconfigs')),
            ],
        ),
    ]
